using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class playerScoreModel 
{
    [RealtimeProperty(1, true, true)]
    private int _playerScore;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class playerScoreModel : RealtimeModel {
    public int playerScore {
        get {
            return _cache.LookForValueInCache(_playerScore, entry => entry.playerScoreSet, entry => entry.playerScore);
        }
        set {
            if (this.playerScore == value) return;
            _cache.UpdateLocalCache(entry => { entry.playerScoreSet = true; entry.playerScore = value; return entry; });
            InvalidateReliableLength();
            FirePlayerScoreDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(playerScoreModel model, T value);
    public event PropertyChangedHandler<int> playerScoreDidChange;
    
    private struct LocalCacheEntry {
        public bool playerScoreSet;
        public int playerScore;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        PlayerScore = 1,
    }
    
    public playerScoreModel() : this(null) {
    }
    
    public playerScoreModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FirePlayerScoreDidChange(int value) {
        try {
            playerScoreDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.PlayerScore, (uint)_playerScore);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.playerScoreSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.PlayerScore, (uint)entry.playerScore);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.PlayerScore, (uint)_playerScore);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.playerScoreSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.playerScoreSet) {
                stream.WriteVarint32((uint)PropertyID.PlayerScore, (uint)entry.playerScore);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.PlayerScore: {
                    int previousValue = _playerScore;
                    _playerScore = (int)stream.ReadVarint32();
                    bool playerScoreExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.playerScoreSet);
                    if (!playerScoreExistsInChangeCache && _playerScore != previousValue) {
                        FirePlayerScoreDidChange(_playerScore);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _playerScore = playerScore;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
