using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class scoreModel
{
    [RealtimeProperty(1, true, true)]
    private string _scoreBoardText;

    

  

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class scoreModel : RealtimeModel {
    public string scoreBoardText {
        get {
            return _cache.LookForValueInCache(_scoreBoardText, entry => entry.scoreBoardTextSet, entry => entry.scoreBoardText);
        }
        set {
            if (this.scoreBoardText == value) return;
            _cache.UpdateLocalCache(entry => { entry.scoreBoardTextSet = true; entry.scoreBoardText = value; return entry; });
            InvalidateReliableLength();
            FireScoreBoardTextDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(scoreModel model, T value);
    public event PropertyChangedHandler<string> scoreBoardTextDidChange;
    
    private struct LocalCacheEntry {
        public bool scoreBoardTextSet;
        public string scoreBoardText;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        ScoreBoardText = 1,
    }
    
    public scoreModel() : this(null) {
    }
    
    public scoreModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireScoreBoardTextDidChange(string value) {
        try {
            scoreBoardTextDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteStringLength((uint)PropertyID.ScoreBoardText, _scoreBoardText);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.scoreBoardTextSet) {
                length += WriteStream.WriteStringLength((uint)PropertyID.ScoreBoardText, entry.scoreBoardText);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteString((uint)PropertyID.ScoreBoardText, _scoreBoardText);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.scoreBoardTextSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.scoreBoardTextSet) {
                stream.WriteString((uint)PropertyID.ScoreBoardText, entry.scoreBoardText);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.ScoreBoardText: {
                    string previousValue = _scoreBoardText;
                    _scoreBoardText = stream.ReadString();
                    bool scoreBoardTextExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.scoreBoardTextSet);
                    if (!scoreBoardTextExistsInChangeCache && _scoreBoardText != previousValue) {
                        FireScoreBoardTextDidChange(_scoreBoardText);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _scoreBoardText = scoreBoardText;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
