using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]

public partial class BallAudioManagerModel

{
    [RealtimeProperty(1,true,true)]
    private float _volume;

    [RealtimeProperty(2, true, true)] 
    private float _pitch;
    
    [RealtimeProperty(3,true,true)]
    private bool _grounded;

    [RealtimeProperty(4,true,true)]
    private int _hitType; //0 == default 1 = player 2 = water

    
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class BallAudioManagerModel : RealtimeModel {
    public float volume {
        get {
            return _cache.LookForValueInCache(_volume, entry => entry.volumeSet, entry => entry.volume);
        }
        set {
            if (this.volume == value) return;
            _cache.UpdateLocalCache(entry => { entry.volumeSet = true; entry.volume = value; return entry; });
            InvalidateReliableLength();
            FireVolumeDidChange(value);
        }
    }
    
    public float pitch {
        get {
            return _cache.LookForValueInCache(_pitch, entry => entry.pitchSet, entry => entry.pitch);
        }
        set {
            if (this.pitch == value) return;
            _cache.UpdateLocalCache(entry => { entry.pitchSet = true; entry.pitch = value; return entry; });
            InvalidateReliableLength();
            FirePitchDidChange(value);
        }
    }
    
    public bool grounded {
        get {
            return _cache.LookForValueInCache(_grounded, entry => entry.groundedSet, entry => entry.grounded);
        }
        set {
            if (this.grounded == value) return;
            _cache.UpdateLocalCache(entry => { entry.groundedSet = true; entry.grounded = value; return entry; });
            InvalidateReliableLength();
            FireGroundedDidChange(value);
        }
    }
    
    public int hitType {
        get {
            return _cache.LookForValueInCache(_hitType, entry => entry.hitTypeSet, entry => entry.hitType);
        }
        set {
            if (this.hitType == value) return;
            _cache.UpdateLocalCache(entry => { entry.hitTypeSet = true; entry.hitType = value; return entry; });
            InvalidateReliableLength();
            FireHitTypeDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(BallAudioManagerModel model, T value);
    public event PropertyChangedHandler<float> volumeDidChange;
    public event PropertyChangedHandler<float> pitchDidChange;
    public event PropertyChangedHandler<bool> groundedDidChange;
    public event PropertyChangedHandler<int> hitTypeDidChange;
    
    private struct LocalCacheEntry {
        public bool volumeSet;
        public float volume;
        public bool pitchSet;
        public float pitch;
        public bool groundedSet;
        public bool grounded;
        public bool hitTypeSet;
        public int hitType;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        Volume = 1,
        Pitch = 2,
        Grounded = 3,
        HitType = 4,
    }
    
    public BallAudioManagerModel() : this(null) {
    }
    
    public BallAudioManagerModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireVolumeDidChange(float value) {
        try {
            volumeDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FirePitchDidChange(float value) {
        try {
            pitchDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireGroundedDidChange(bool value) {
        try {
            groundedDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireHitTypeDidChange(int value) {
        try {
            hitTypeDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteFloatLength((uint)PropertyID.Volume);
            length += WriteStream.WriteFloatLength((uint)PropertyID.Pitch);
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Grounded, _grounded ? 1u : 0u);
            length += WriteStream.WriteVarint32Length((uint)PropertyID.HitType, (uint)_hitType);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.volumeSet) {
                length += WriteStream.WriteFloatLength((uint)PropertyID.Volume);
            }
            if (entry.pitchSet) {
                length += WriteStream.WriteFloatLength((uint)PropertyID.Pitch);
            }
            if (entry.groundedSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.Grounded, entry.grounded ? 1u : 0u);
            }
            if (entry.hitTypeSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.HitType, (uint)entry.hitType);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteFloat((uint)PropertyID.Volume, _volume);
            stream.WriteFloat((uint)PropertyID.Pitch, _pitch);
            stream.WriteVarint32((uint)PropertyID.Grounded, _grounded ? 1u : 0u);
            stream.WriteVarint32((uint)PropertyID.HitType, (uint)_hitType);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.volumeSet || entry.pitchSet || entry.groundedSet || entry.hitTypeSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.volumeSet) {
                stream.WriteFloat((uint)PropertyID.Volume, entry.volume);
                didWriteProperties = true;
            }
            if (entry.pitchSet) {
                stream.WriteFloat((uint)PropertyID.Pitch, entry.pitch);
                didWriteProperties = true;
            }
            if (entry.groundedSet) {
                stream.WriteVarint32((uint)PropertyID.Grounded, entry.grounded ? 1u : 0u);
                didWriteProperties = true;
            }
            if (entry.hitTypeSet) {
                stream.WriteVarint32((uint)PropertyID.HitType, (uint)entry.hitType);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Volume: {
                    float previousValue = _volume;
                    _volume = stream.ReadFloat();
                    bool volumeExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.volumeSet);
                    if (!volumeExistsInChangeCache && _volume != previousValue) {
                        FireVolumeDidChange(_volume);
                    }
                    break;
                }
                case (uint)PropertyID.Pitch: {
                    float previousValue = _pitch;
                    _pitch = stream.ReadFloat();
                    bool pitchExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.pitchSet);
                    if (!pitchExistsInChangeCache && _pitch != previousValue) {
                        FirePitchDidChange(_pitch);
                    }
                    break;
                }
                case (uint)PropertyID.Grounded: {
                    bool previousValue = _grounded;
                    _grounded = (stream.ReadVarint32() != 0);
                    bool groundedExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.groundedSet);
                    if (!groundedExistsInChangeCache && _grounded != previousValue) {
                        FireGroundedDidChange(_grounded);
                    }
                    break;
                }
                case (uint)PropertyID.HitType: {
                    int previousValue = _hitType;
                    _hitType = (int)stream.ReadVarint32();
                    bool hitTypeExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.hitTypeSet);
                    if (!hitTypeExistsInChangeCache && _hitType != previousValue) {
                        FireHitTypeDidChange(_hitType);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _volume = volume;
        _pitch = pitch;
        _grounded = grounded;
        _hitType = hitType;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
